//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CMMM.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CMMMParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICMMMVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CMMMParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CMMMParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CMMMParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.quoteExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuoteExpr([NotNull] CMMMParser.QuoteExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] CMMMParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.assignStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] CMMMParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.declareStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStatement([NotNull] CMMMParser.DeclareStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] CMMMParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] CMMMParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] CMMMParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] CMMMParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.commonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommonExpression([NotNull] CMMMParser.CommonExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.assignAbleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignAbleStatement([NotNull] CMMMParser.AssignAbleStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.declareExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareExpression([NotNull] CMMMParser.DeclareExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CMMMParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.andAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndAndExpression([NotNull] CMMMParser.AndAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.cmpExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCmpExpression([NotNull] CMMMParser.CmpExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.addExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpression([NotNull] CMMMParser.AddExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.mulExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulExpression([NotNull] CMMMParser.MulExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] CMMMParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] CMMMParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.variableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableExpression([NotNull] CMMMParser.VariableExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.basicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicType([NotNull] CMMMParser.BasicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarators([NotNull] CMMMParser.DeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] CMMMParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMMParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericLiteral([NotNull] CMMMParser.NumericLiteralContext context);
}
