//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CMM.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CMMParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ICMMVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] CMMParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CMMParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CMMParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CMMParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] CMMParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.boolExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolExpression([NotNull] CMMParser.BoolExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] CMMParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] CMMParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] CMMParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] CMMParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CMMParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] CMMParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] CMMParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerList([NotNull] CMMParser.InitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CMMParser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] CMMParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.parameterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterClause([NotNull] CMMParser.ParameterClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] CMMParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] CMMParser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.assignStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] CMMParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] CMMParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.leftValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftValue([NotNull] CMMParser.LeftValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] CMMParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] CMMParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] CMMParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.forInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitializer([NotNull] CMMParser.ForInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CMMParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseClause([NotNull] CMMParser.ElseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadStatement([NotNull] CMMParser.ReadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.writeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWriteStatement([NotNull] CMMParser.WriteStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] CMMParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallStatement([NotNull] CMMParser.CallStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CMMParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeBlock([NotNull] CMMParser.CodeBlockContext context);
}
